# Generated by Django 4.1.13 on 2024-03-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iid', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('phonenumber', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('Comments', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Feed',
            },
        ),
    ]
