# Generated by Django 4.1.13 on 2024-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
