# Generated by Django 4.1.13 on 2024-03-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feed_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
