# Generated by Django 4.1.13 on 2024-04-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogacore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='raa',
            new_name='Login',
        ),
        migrations.RenameModel(
            old_name='lopa',
            new_name='Signup',
        ),
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
        migrations.AlterModelTable(
            name='signup',
            table='Signup',
        ),
    ]
