# Generated by Django 4.1.13 on 2024-04-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogacore', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
