# Generated by Django 4.1.13 on 2024-04-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogacore', '0005_profile_username_alter_profile_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
