# Generated by Django 4.1.13 on 2024-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogacore', '0006_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(default='KLU', max_length=10),
        ),
    ]
